/**
 * File: index.ts
 * Purpose: Expose the shared Quake II runtime core modules.
 *
 * This file is not a direct source port.
 * It is a package entry point for shared runtime exports.
 *
 * Dependencies:
 * - packages/qcommon/src/q-shared.ts
 */

export {
  ALIAS_LOOP_COUNT,
  Cbuf_AddText,
  Cbuf_CopyToDefer,
  Cbuf_Execute,
  Cbuf_ExecuteText,
  Cbuf_Init,
  Cbuf_InsertFromDefer,
  Cbuf_InsertText,
  Cmd_AddCommand,
  Cmd_Argc,
  Cmd_Args,
  Cmd_Argv,
  Cmd_Alias_f,
  Cmd_CompleteCommand,
  Cmd_ExecuteString,
  Cmd_Exists,
  Cmd_Init,
  Cmd_RemoveCommand,
  Cmd_TokenizeString,
  Cmd_Wait_f,
  EXEC_APPEND,
  EXEC_INSERT,
  EXEC_NOW,
  createCommandRuntime
} from "./cmd.js";

export {
  CVAR_ARCHIVE,
  CVAR_LATCH,
  CVAR_NOSET,
  CVAR_SERVERINFO,
  CVAR_USERINFO,
  Cvar_BitInfo,
  Cvar_Command,
  Cvar_CompleteVariable,
  Cvar_FindVar,
  Cvar_ForceSet,
  Cvar_FullSet,
  Cvar_Get,
  Cvar_GetLatchedVars,
  Cvar_InfoValidate,
  Cvar_Init,
  Cvar_List_f,
  Cvar_Serverinfo,
  Cvar_Set,
  Cvar_Set2,
  Cvar_Set_f,
  Cvar_SetServerState,
  Cvar_SetValue,
  Cvar_WriteVariables,
  Cvar_Userinfo,
  Cvar_VariableString,
  Cvar_VariableValue,
  createCvarRuntime
} from "./cvar.js";

export { createQcommonRuntime } from "./runtime.js";
export {
  COM_AddParm,
  COM_Argc,
  COM_Argv,
  COM_CheckParm,
  COM_ClearArgv,
  COM_InitArgv,
  Com_BeginRedirect,
  Com_EndRedirect,
  Com_Printf,
  createCommonRuntime,
  Info_Print
} from "./common.js";

export {
  ANGLE2SHORT,
  AREA_SOLID,
  AREA_TRIGGERS,
  ATTN_IDLE,
  ATTN_NONE,
  ATTN_NORM,
  ATTN_STATIC,
  BUTTON_ANY,
  BUTTON_ATTACK,
  BUTTON_USE,
  CHAN_AUTO,
  CHAN_BODY,
  CHAN_ITEM,
  CHAN_NO_PHS_ADD,
  CHAN_RELIABLE,
  CHAN_VOICE,
  CHAN_WEAPON,
  CS_AIRACCEL,
  CS_CDTRACK,
  CS_GENERAL,
  CS_IMAGES,
  CS_ITEMS,
  CS_LIGHTS,
  CS_MAPCHECKSUM,
  CS_MAXCLIENTS,
  CS_MODELS,
  CS_NAME,
  CS_PLAYERSKINS,
  CS_SKY,
  CS_SKYAXIS,
  CS_SKYROTATE,
  CS_SOUNDS,
  CS_STATUSBAR,
  EF_ANIM01,
  EF_ANIM23,
  EF_ANIM_ALL,
  EF_ANIM_ALLFAST,
  EF_BFG,
  EF_BLASTER,
  EF_BLUEHYPERBLASTER,
  EF_COLOR_SHELL,
  EF_FLIES,
  EF_FLAG1,
  EF_FLAG2,
  EF_GIB,
  EF_GRENADE,
  EF_GREENGIB,
  EF_HALF_DAMAGE,
  EF_HYPERBLASTER,
  EF_IONRIPPER,
  EF_PENT,
  EF_PLASMA,
  EF_POWERSCREEN,
  EF_QUAD,
  EF_ROCKET,
  EF_ROTATE,
  EF_SPINNINGLIGHTS,
  EF_SPHERETRANS,
  EF_TAGTRAIL,
  EF_TELEPORTER,
  EF_TRACKER,
  EF_TRACKERTRAIL,
  MASK_ALL,
  MASK_CURRENT,
  MASK_DEADSOLID,
  MASK_MONSTERSOLID,
  MASK_OPAQUE,
  MASK_PLAYERSOLID,
  MASK_SHOT,
  MASK_SOLID,
  MASK_WATER,
  MAX_CLIENTS,
  MAX_CONFIGSTRINGS,
  MAX_EDICTS,
  MAX_GENERAL,
  MAX_IMAGES,
  MAX_INFO_KEY,
  MAX_INFO_STRING,
  MAX_INFO_VALUE,
  MAX_ITEMS,
  MAX_LIGHTSTYLES,
  MAX_MODELS,
  MAX_OSPATH,
  MAX_QPATH,
  MAX_SOUNDS,
  MAX_STATS,
  MAX_STRING_CHARS,
  MAX_STRING_TOKENS,
  MAX_TOKEN_CHARS,
  MAXTOUCH,
  PMF_DUCKED,
  PMF_JUMP_HELD,
  PMF_NO_PREDICTION,
  PMF_ON_GROUND,
  PMF_TIME_LAND,
  PMF_TIME_TELEPORT,
  PMF_TIME_WATERJUMP,
  PRINT_ALERT,
  PRINT_ALL,
  PRINT_CHAT,
  PRINT_DEVELOPER,
  PRINT_HIGH,
  PRINT_LOW,
  PRINT_MEDIUM,
  RF_BEAM,
  RF_CUSTOMSKIN,
  RF_DEPTHHACK,
  RF_FRAMELERP,
  RF_FULLBRIGHT,
  RF_GLOW,
  RF_IR_VISIBLE,
  RF_MINLIGHT,
  RF_SHELL_BLUE,
  RF_SHELL_DOUBLE,
  RF_SHELL_GREEN,
  RF_SHELL_HALF_DAM,
  RF_SHELL_RED,
  RF_TRANSLUCENT,
  RF_USE_DISGUISE,
  RF_VIEWERMODEL,
  RF_WEAPONMODEL,
  RDF_IRGOGGLES,
  RDF_NOWORLDMODEL,
  RDF_UNDERWATER,
  RDF_UVGOGGLES,
  SHORT2ANGLE,
  STAT_AMMO,
  STAT_AMMO_ICON,
  STAT_ARMOR,
  STAT_ARMOR_ICON,
  STAT_CHASE,
  STAT_FLASHES,
  STAT_FRAGS,
  STAT_HEALTH,
  STAT_HEALTH_ICON,
  STAT_HELPICON,
  STAT_LAYOUTS,
  STAT_PICKUP_ICON,
  STAT_PICKUP_STRING,
  STAT_SELECTED_ICON,
  STAT_SELECTED_ITEM,
  STAT_SPECTATOR,
  STAT_TIMER,
  STAT_TIMER_ICON,
  createEntityState,
  createPlayerState
} from "./q-shared.js";

export {
  MSG_BeginReading,
  MSG_ReadAngle,
  MSG_ReadAngle16,
  MSG_ReadByte,
  MSG_ReadChar,
  MSG_ReadCoord,
  MSG_ReadData,
  MSG_ReadFloat,
  MSG_ReadLong,
  MSG_ReadPos,
  MSG_ReadShort,
  MSG_ReadString,
  MSG_ReadStringLine,
  MSG_WriteAngle,
  MSG_WriteAngle16,
  MSG_WriteByte,
  MSG_WriteChar,
  MSG_WriteCoord,
  MSG_WriteFloat,
  MSG_WriteLong,
  MSG_WritePos,
  MSG_WriteShort,
  MSG_WriteString
} from "./messages.js";

export {
  entity_event_t,
  multicast_t,
  pmtype_t,
  temp_event_t
} from "./q-shared.js";

export type {
  CommandAlias,
  CommandHooks,
  CommandRegistration,
  CommandRuntime,
  xcommand_t
} from "./cmd.js";

export type {
  CvarHooks,
  CvarRuntime,
  cvar_t
} from "./cvar.js";

export type { QcommonRuntime, QcommonRuntimeOptions } from "./runtime.js";
export type { CommonRuntime } from "./common.js";

export type {
  byte,
  cmodel_t,
  cplane_t,
  csurface_t,
  entity_state_t,
  player_state_t,
  pmove_state_t,
  pmove_t,
  qboolean,
  trace_t,
  usercmd_t,
  vec3_t,
  vec5_t,
  vec_t
} from "./q-shared.js";
