/**
 * File: quake2-web-config-write.ts
 * Purpose: Verify browser persistence for the logical `baseq2/config.cfg` generated by CL_WriteConfiguration.
 *
 * This file is not a direct source port.
 * It checks that the web adapter stores Quake II config contents as a logical file rather than exposing localStorage to engine code.
 *
 * Dependencies:
 * - apps/web/src/web-config-storage.ts
 * - packages/client/src/cl_main.ts
 * - packages/filesystem
 * - packages/qcommon
 */

import { strict as assert } from "node:assert";

import {
  K_TAB,
  Key_Init,
  createClientKeyContext,
  createClientRuntime
} from "../../packages/client/src/index.js";
import {
  CL_InitLocal,
  CL_WriteConfiguration,
  createClientMainContext
} from "../../packages/client/src/cl_main.js";
import {
  createVirtualFilesystem
} from "../../packages/filesystem/src/index.js";
import {
  CVAR_ARCHIVE,
  Cvar_Get,
  createCommandRuntime,
  createCvarRuntime
} from "../../packages/qcommon/src/index.js";
import {
  createWebConfigStorage,
  readWebConfigOrMountedText,
  toConfigStorageKey,
  type WebStorageLike
} from "../../apps/web/src/web-config-storage.js";

const backing = new Map<string, string>();
const storageLike: WebStorageLike = {
  getItem: (key) => backing.get(key) ?? null,
  setItem: (key, value) => {
    backing.set(key, value);
  },
  removeItem: (key) => {
    backing.delete(key);
  }
};

const filesystem = createVirtualFilesystem();
const storage = createWebConfigStorage(storageLike);
const client = createClientRuntime();
const cmd = createCommandRuntime();
const cvar = createCvarRuntime();
const keys = createClientKeyContext({ client, cmd, cvar });
const main = createClientMainContext(client, cmd, cvar);

Key_Init(keys);
CL_InitLocal(main);

keys.state.keybindings[K_TAB] = "inven";
Cvar_Get(cvar, "phase2_archive_test", "restored", CVAR_ARCHIVE);

const write = CL_WriteConfiguration(main, {
  keyContext: keys,
  getGameDir: () => "baseq2",
  onWriteConfigFile: (path, contents) => storage.writeText(path, contents)
});

assert.equal(write?.path, "baseq2/config.cfg", "CL_WriteConfiguration should target baseq2/config.cfg");
const stored = backing.get(toConfigStorageKey("baseq2/config.cfg")) ?? "";
assert.equal(stored.length > 0, true, "config.cfg should be persisted in web storage");
assert.equal(stored.includes("// generated by quake, do not modify\n"), true, "config header mismatch");
assert.equal(stored.includes("bind TAB \"inven\"\n"), true, "key bindings should be serialized");
assert.equal(stored.includes("set phase2_archive_test \"restored\"\n"), true, "archive cvars should be serialized");
assert.equal(
  readWebConfigOrMountedText(storage, filesystem, "config.cfg"),
  stored,
  "persisted config.cfg should be readable through the phase 1 overlay"
);

console.log("quake2-web-config-write: ok");
